User.destroy_all
Recipe.destroy_all
Ingredient.destroy_all
RecipeIngredient.destroy_all

u1 = User.create(name: "Harriet")
u2 = User.create(name: "Richie")
u3 = User.create(name: "Danny")
u4 = User.create(name: "Dunia")
u5 = User.create(name: "Patrick")

r1 = Recipe.create(title: "Scrambled Tofu on toast")
r2 = Recipe.create(title: "Chilli Con Carne")
r3 = Recipe.create(title: "Massamun Beef Curry")
r4 = Recipe.create(title: "Mushroom Risotto")
r5 = Recipe.create(title: "Lentil Dahl")
r6 = Recipe.create(title: "Fish Pie")
r7 = Recipe.create(title: "Miso Baked Cod")
r8 = Recipe.create(title: "Green Bean Yakisoba")
r9 = Recipe.create(title: "Baked Alaska")
r10 = Recipe.create(title: "Mille Feuille")

tofu = Ingredient.create(name: "Tofu")
rice = Ingredient.create(name: "Rice")
cod = Ingredient.create(name: "Cod")
lentils = Ingredient.create(name: "Lentils")
mushrooms = Ingredient.create(name: "Mushrooms")
pastry = Ingredient.create(name: "Pastry")
potatoes = Ingredient.create(name: "Potatoes")
beans = Ingredient.create(name: "Green Beans")
noodles = Ingredient.create(name: "Noodles")
sugar = Ingredient.create(name: "Sugar")
egg = Ingredient.create(name: "Egg")
beef = Ingredient.create(name: "Beef")
chilli = Ingredient.create(name: "Chilli")
tomatoes = Ingredient.create(name: "Tomatoes")
soy = Ingredient.create(name: "Soy Sauce")
coconut = Ingredient.create(name: "Coconut milk")
turmeric = Ingredient.create(name: "turmeric")
spring_onion = Ingredient.create(name: "Spring onion")
bread = Ingredient.create(name: "Bread")
curry = Ingredient.create(name: "Curry paste")
cheese = Ingredient.create(name: "Cheese")
strawberry = Ingredient.create(name: "Strawberry")
ice_cream = Ingredient.create(name: "Ice Cream")

r1.create_recipe_ingredients(tofu, turmeric, spring_onion, bread)
r2.create_recipe_ingredients(beef, chilli, tomatoes, rice)
r3.create_recipe_ingredients(beef, potatoes, chilli, curry, rice, coconut)
r4.create_recipe_ingredients(rice, mushrooms, cheese)
r5.create_recipe_ingredients(lentils, chilli, curry, turmeric, tomatoes)
r6.create_recipe_ingredients(cod, potatoes, egg, cheese)
r7.create_recipe_ingredients(soy, cod, spring_onion, chilli)
r8.create_recipe_ingredients(soy, noodles, beans, sugar, egg, chilli, spring_onion)
r9.create_recipe_ingredients(egg, sugar, ice_cream)
r10.create_recipe_ingredients(pastry, egg, sugar, strawberry)

r1.update(content: "Crumble tofu. Fry in oil and turmeric. Sprinkle spring onions.")
r2.update(content: "Chop and fry onions. Add beef and chilli. Cook. Serve. Eat. Enjoy.")
r3.update(content: "Fry curry paste with beef. Add coconut milk. Add potatoes and chilli. Serve with rice.")
r4.update(content: "Fry onion and garlic. Add rice. Add stock slowly. Add cheese before serving.")
r5.update(content: "Fry curry paste, chilli and turmeric. Add lentils, tomatoes and water. Boil forever.")
r6.update(content: "Cook fish. Layer in oven dish with boiled eggs and potatoes. Sprinkle cheese and bake.")
r7.update(content: "No one has any idea how to make this.")
r8.update(content: "Big wok. Beans. Chilli. Noodles. Done.")
r9.update(content: "Put the ice cream in the oven and pray.")
r10.update(content: "Pronounced 'Mill Foy' if you're English.")
