User.destroy_all
Recipe.destroy_all
Ingredient.destroy_all
RecipeIngredient.destroy_all

u1 = User.create(name: "Harriet")
u2 = User.create(name: "Richie")
u3 = User.create(name: "Danny")
u4 = User.create(name: "Dunia")
u5 = User.create(name: "Patrick")

r1 = Recipe.create(title: "Scrambled Tofu on toast")
r2 = Recipe.create(title: "Chilli Con Carne")
r3 = Recipe.create(title: "Massamun Beef Curry")
r4 = Recipe.create(title: "Mushroom Risotto")
r5 = Recipe.create(title: "Lentil Dahl")
r6 = Recipe.create(title: "Fish Pie")
r7 = Recipe.create(title: "Miso Baked Cod")
r8 = Recipe.create(title: "Green Bean Yakisoba")
r9 = Recipe.create(title: "Baked Alaska")
r10 = Recipe.create(title: "Mille Feuille")

tofu = Ingredient.create(name: "Tofu")
rice = Ingredient.create(name: "Rice")
cod = Ingredient.create(name: "Cod")
lentils = Ingredient.create(name: "Lentils")
mushrooms = Ingredient.create(name: "Mushrooms")
pastry = Ingredient.create(name: "Pastry")
potatoes = Ingredient.create(name: "Potatoes")
beans = Ingredient.create(name: "Green Beans")
noodles = Ingredient.create(name: "Noodles")
sugar = Ingredient.create(name: "Sugar")
egg = Ingredient.create(name: "Egg")
beef = Ingredient.create(name: "Beef")
chilli = Ingredient.create(name: "Chilli")
tomatoes = Ingredient.create(name: "Tomatoes")
soy = Ingredient.create(name: "Soy Sauce")
coconut = Ingredient.create(name: "Coconut milk")
turmeric = Ingredient.create(name: "turmeric")
spring_onion = Ingredient.create(name: "Spring onion")
bread = Ingredient.create(name: "Bread")
curry = Ingredient.create(name: "Curry paste")
cheese = Ingredient.create(name: "Cheese")
strawberry = Ingredient.create(name: "Strawberry")
ice_cream = Ingredient.create(name: "Ice Cream")

r1.create_recipe_ingredients(tofu, turmeric, spring_onion, bread)
r2.create_recipe_ingredients(beef, chilli, tomatoes, rice)
r3.create_recipe_ingredients(beef, potatoes, chilli, curry, rice)
r4.create_recipe_ingredients(rice, mushrooms, cheese)
r5.create_recipe_ingredients(lentils, chilli, curry, turmeric, tomatoes)
r6.create_recipe_ingredients(cod, potatoes, egg, spring_onion, cheese)
r7.create_recipe_ingredients(soy, cod, spring_onion, chilli)
r8.create_recipe_ingredients(soy, noodles, beans, sugar, egg, chilli)
r9.create_recipe_ingredients(egg, sugar)
r10.create_recipe_ingredients(pastry, egg, sugar, strawberry)
